spring:
  application:
    name: msnetlivros
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: postgresql://localhost:5432/netlivros
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 0