package com.example.NetLivros.livro.enums;

public enum Genero {

	AUTOAJUDA, ROMANCE, TERROR, FICCAO, COMEDIA, AVENTURA, FANTASIA, FICÇÃO_CIENTÍFICA, DISTOPIA, AÇÃO_E_AVENTURA,
	FICÇÃO_POLICIAL, HORROR, THRILLER_E_SUSPENSE, FICÇÃO_HISTÓRICA, NOVELA, FICÇÃO_FEMININA, LGBTQ,
	FICÇÃO_CONTEMPORÂNEA, REALISMO_MÁGICO, GRAPHIC_NOVEL, CONTO, YOUNG_ADULT, NEW_ADULT, INFANTIL,
	MEMÓRIAS_E_AUTOBIOGRAFIA, BIOGRAFIA, GASTRONOMIA, ARTE_E_FOTOGRAFIA, HISTÓRIA, VIAGEM, CRIMES_REAIS, HUMOR, ENSAIOS,
	GUIAS_E_COMO_FAZER, RELIGIÃO_E_ESPIRITUALIDADE, HUMANIDADES_E_CIÊNCIAS_SOCIAIS, PATERNIDADE_E_FAMÍLIA,
	TECNOLOGIA_E_CIÊNCIA;
}
