package com.example.NetLivros.livro.enums;

public enum Genrer {

	SELF_HELP, ROMANCE, HORROR, FICTION, COMEDY, ADVENTURE, FANTASY, SCIENCE_FICTION, DYSTOPIA, ACTION_AND_ADVENTURE,
	POLICE_FICTION, THRILLER_AND_SUSPENSE, HISTORICAL_FICTION, NOVELA, WOMENS_FICTION, LGBTQ,
	CONTEMPORARY_FICTION, MAGIC_REALISM, GRAPHIC_NOVEL, STORY, YOUNG_ADULT, NEW_ADULT, CHILDREN,
	MEMORIES_AND_AUTOBIOGRAPHY, BIOGRAPHY, GASTRONOMY, ART_AND_PHOTOGRAPHY, HISTORY, TRAVEL, REAL_CRIMES, HUMOR, ESSAYS,
	GUIDES_AND_HOW_TO_DO_IT, RELIGION_AND_SPIRITUALITY, HUMANITIES_AND_SOCIAL_SCIENCES, FATHERHOOD_AND_FAMILY,
	TECHNOLOGY_AND_SCIENCE;
}
