spring:
  application:
    name: msnetlivros
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: vousuaveagencia@gmail.com
    password: tmireetgdzlopaks
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
            

  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/netlivros?createDatabaseIfNotExist=true
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8080
  
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#      instance:
#        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}